# Generated by Django 5.2.7 on 2025-10-13 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emprunteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloque', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='JeuDePlateau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('createur', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DVD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('disponible', models.BooleanField(default=True)),
                ('date_emprunt', models.DateField(blank=True, null=True)),
                ('realisateur', models.CharField(max_length=100)),
                ('emprunteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bibliothecaire.emprunteur')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('disponible', models.BooleanField(default=True)),
                ('date_emprunt', models.DateField(blank=True, null=True)),
                ('artiste', models.CharField(max_length=100)),
                ('emprunteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bibliothecaire.emprunteur')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('disponible', models.BooleanField(default=True)),
                ('date_emprunt', models.DateField(blank=True, null=True)),
                ('auteur', models.CharField(max_length=100)),
                ('emprunteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bibliothecaire.emprunteur')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateField(auto_now_add=True)),
                ('date_retour', models.DateField(blank=True, null=True)),
                ('cd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bibliothecaire.cd')),
                ('dvd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bibliothecaire.dvd')),
                ('emprunteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliothecaire.emprunteur')),
                ('livre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bibliothecaire.livre')),
            ],
        ),
        migrations.AddField(
            model_name='emprunteur',
            name='membre',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bibliothecaire.membre'),
        ),
    ]
