# Generated by Django 5.2.7 on 2025-10-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliothecaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='nombre_emprunts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
